version: "3.8"
services:
  web:
    container_name: eat-now-frontend
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - application

networks:
  application:
    driver: bridge
